# 配置文件
DAILY_TIME: "8:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2022-08-28" # 纪念日
CITY: "内江"

BIRTHDAY:
  - "08-26"

APP_ID: "wxf3175cc682697586"
APP_SECRET: "e9a138d1458d3aaed926b259787aafba"

USER_ID: 
  - "o-i3L6ZoYBthdWEwII5z52Xb8u_4"
  # - "o-i3L6Y1THo9QpiBRAlnZCEqBIy0"
  - "o-i3L6Y1THo9QpiBRAlnZCEqBIy0" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "9BwuCSedbULaZrNcSvsk8e0dOrZeQyt8qFEotfQ03U8"
